### ISSUE TITLE
Portuguese model

### ISSUE THREAD

**Issue by GuiJordao21** [ibm-dev/watson-streaming-stt#1]
It doesn't work with the portuguese model, do you have any idea why?

**Comment by sdague** [comment]
I don't, it's been a little bit since I've actively used this code. You just patched out the model in the URL to try Portuguese? Would be happy to experiment if you have a Portuguese wav file that I can use to simulate the stream.

**Comment by GuiJordao21** [comment]
Yes, i just changed to pt-BR_BroadbandModel

Here is a really simple wav file
[file_2.zip](https://github.com/ibm-dev/watson-streaming-stt/files/1604027/file_2.zip)

**Comment by stevemar** [comment]
closing this issue as this repo will no longer be actively maintained and be put in read-only mode
