### ISSUE TITLE
Credentials in call to WebSocketApp

### ISSUE THREAD

**Issue by webcast33** [ibm-dev/watson-streaming-stt#3]
Your coding example here looks exactly like what I need for my project. The problem is that I can't get past the WebSocketApp call because of 401 (Not Authorized) handshake status codes. The IBM Bluemix screen for Watson STT no longer returns a username and password. I do have an API key, but I can't figure out how to pass it to WebSocketApp to make a connection.

Could you please explain or perhaps update the Python script? Thank you very much.

**Comment by sdague** [comment]
should be fixed in master now with new example

**Comment by webcast33** [comment]
Worked perfectly! Thank you very much.
